Repository KaizeNodeLabs/SafeSwap, pull requests merged in 2024-12, with the labels that each got.

#39 feat/add safe swap logo
  frontend/app/components/ui/SafeSwapLogo.tsx
  frontend/app/components/ui/footer.tsx
  frontend/app/components/ui/hero-section.tsx
  frontend/app/page.tsx
  frontend/public/images/logo-dark.svg
  frontend/public/images/logo-light.svg
  logo-usage.md
Labels: ODHack10, actual: 2

#43 docs: update README and PR template
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: enhancement

#45 docs: add contribution guidelines for new contributors
  CONTRIBUTION_GUIDELINES.md
  GIT_GUIDELINES.md
  ISSUES_GUIDELINES.md
  docs/CONTRIBUTION_GUIDELINES.md
  docs/GIT_GUIDELINES.md
  docs/ISSUES_GUIDELINES.md
Labels: documentation, actual: 1

#66 Add button cart
  frontend/app/marketplace/page.tsx
Labels: ODHack11

#67 refactor: unify marketplace & landing header
  frontend/app/components/ui/header.tsx
  frontend/app/marketplace/page.tsx
  frontend/app/page.tsx
Labels: ODHack11

#72 Feat: pagination and results selector
  frontend/app/components/marketplace/index.ts
  frontend/app/components/marketplace/products-pagination.tsx
  frontend/app/components/ui/button.tsx
  frontend/app/components/ui/pagination.tsx
  frontend/app/components/ui/select.tsx
  frontend/app/marketplace/page.tsx
  frontend/bun.lockb
  frontend/package.json
Labels: ODHack11

#68 feat: Remove the 'Connect Wallet' button from the Hero section
  frontend/app/components/ui/hero-section.tsx
Labels: actual: 1, ODHack11

#69 feat: Integrate Footer into global layout for consistent design
  frontend/app/components/ui/SafeSwapLogo.tsx
  frontend/app/components/ui/footer.tsx
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: actual: 2, ODHack11

#71 feat: Replace product card carousel with a single static image
  frontend/app/components/ui/button.tsx
  frontend/app/components/ui/card.tsx
  frontend/app/components/ui/carousel.tsx
  frontend/app/components/ui/image-carrousel.tsx
  frontend/app/marketplace/page.tsx
  frontend/bun.lockb
  frontend/package.json
Labels: actual: 2, ODHack11

#70 feat: Create User Button in Header with Dropdown Menu
  frontend/app/components/ui/dropdown-menu.tsx
  frontend/app/components/ui/header.tsx
  frontend/app/marketplace/page.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: actual: 2, ODHack11

#74 feat: Add Breadcrumb Navigation to Marketplace
  frontend/app/components/ui/breadcrumb-navigation.tsx
  frontend/app/marketplace/page.tsx
  package.json
Labels: ODHack11

#75 Feat/product details and refactor
  frontend/app/components/Bounded.tsx
  frontend/app/components/header/Header.tsx
  frontend/app/components/header/subheader/SubHeader.tsx
  frontend/app/components/products/Images.tsx
  frontend/app/components/sidebar/Sidebar.tsx
  frontend/app/components/ui/header.tsx
  frontend/app/components/ui/sidebar.tsx
  frontend/app/layout.tsx
  frontend/app/marketplace/page.tsx
  frontend/app/page.tsx
  frontend/app/products/[productId]/page.tsx
  frontend/app/products/page.tsx
  frontend/constants/testDataProduct.ts
  frontend/entities/Product.ts
  frontend/package-lock.json
  frontend/utils/utils.hook.ts
Labels: actual: 3, ODHack11

#76 Feat/add click event to image and tittle on product card
  frontend/app/products/page.tsx
  frontend/package-lock.json
Labels: actual: 1, ODHack11

#77 Feat: delivery button
  frontend/app/components/header/Header.tsx
  frontend/app/components/ui/delivery-location-button.tsx
  frontend/app/components/ui/select.tsx
  frontend/bun.lockb
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/costarica.svg
Labels: ODHack11

#78 Style/standardize productuploadmodal design
  frontend/app/components/header/subheader/SubHeader.tsx
  frontend/app/components/ui/add-product-modal.tsx
  frontend/app/components/ui/input.tsx
  frontend/app/components/ui/label.tsx
  frontend/app/components/ui/product-upload-modal.tsx
  frontend/app/components/ui/textarea.tsx
Labels: ODHack11

#80 feat: implement shadcn dark mode
  frontend/app/components/header/Header.tsx
  frontend/app/components/header/subheader/SubHeader.tsx
  frontend/app/components/products/ProductDetailModal.tsx
  frontend/app/components/providers/theme-provider.tsx
  frontend/app/components/ui/add-product-modal.tsx
  frontend/app/components/ui/breadcrumb-navigation.tsx
  frontend/app/components/ui/delivery-location-button.tsx
  frontend/app/components/ui/input.tsx
  frontend/app/components/ui/label.tsx
  frontend/app/components/ui/select.tsx
  frontend/app/components/ui/textarea.tsx
  frontend/app/components/ui/theme-toggle.tsx
  frontend/app/layout.tsx
  frontend/app/marketplace/page.tsx
  frontend/app/products/[productId]/page.tsx
  frontend/app/products/page.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: actual: 2, ODHack11

#81 feat: enhance feature section with clickable links in descriptions
  frontend/app/components/ui/feature-section.tsx
Labels: actual: 1, ODHack11
