Repository KaizeNodeLabs/SafeSwap, pull requests merged in 2024-11, with the labels that each got.

#8 Create ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: documentation

#7 Feature: SafeSwap Frontend Boilerplate
  .cursorrules
  .gitignore
  .lefthook/commit-msg/template_checker.sh
  README.md
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/README.md
  frontend/app/components/ui/button.tsx
  frontend/app/components/ui/feature-section.tsx
  frontend/app/components/ui/hero-section.tsx
  frontend/app/components/ui/stats-section.tsx
  frontend/app/favicon.ico
  frontend/app/fonts/GeistMonoVF.woff
  frontend/app/fonts/GeistVF.woff
  frontend/app/globals.css
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/biome.json
  frontend/bun.lockb
  frontend/components.json
  frontend/instructions/instructions.md
  frontend/lib/utils.ts
  frontend/next.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.mjs
  frontend/tailwind.config.ts
  frontend/tsconfig.json
  lefthook.yml
  package-lock.json
  package.json
Labels: enhancement

#9 Feat: Create .github/workflows directory
  .github/workflows/auto-assign.yml
  .github/workflows/placeholder.yml
Labels: enhancement

#10 UI enhancement
  frontend/app/components/ui/card.tsx
  frontend/app/components/ui/checkbox.tsx
  frontend/app/components/ui/hero-section.tsx
  frontend/app/components/ui/input.tsx
  frontend/app/components/ui/sidebar.tsx
  frontend/app/components/ui/slider.tsx
  frontend/app/marketplace/page.tsx
Labels: enhancement

#27 Feat/add safeswap landing page
  frontend/app/components/ui/hero-section.tsx
  frontend/app/components/ui/input.tsx
  frontend/app/marketplace/page.tsx
Labels: ODHack10, actual: 1

#34 Fix: GA Auto assign prs
  .github/workflows/auto-assign.yml
Labels: bug, ODHack10, actual: 1

#33 POC: Enhance Filter UI
  frontend/app/components/ui/sidebar.tsx
  frontend/app/components/ui/slider.tsx
  frontend/app/marketplace/page.tsx
Labels: ODHack10, actual: 2

#35 Create a form to upload a product
  frontend/app/components/ui/product-upload-modal.tsx
  frontend/app/marketplace/page.tsx
Labels: ODHack10, actual: 2

#25 chore: add connect button to markerplace
  frontend/app/marketplace/page.tsx
  frontend/app/page.tsx
Labels: ODHack10, actual: 1

#37 Feature 🚀: Add view details for the product #20
  frontend/app/components/products/ProductDetailModal.tsx
  frontend/app/marketplace/page.tsx
  frontend/app/page.tsx
Labels: ODHack10, actual: 2
